services:
    redis:
        image: redis
        container_name: redis_container
        ports:
            - "6379:6379"
    api:
        build:
            #context: ./RedisAsDb.API/
            dockerfile: ./RedisAsDb.API/Dockerfile
        container_name: redis_api
        ports:
            - "80:4000"
            - "4000:4001"
        environment:
            - ASPNETCORE_ENVIRONMENT=Test
        depends_on:
            redis:
                condition: service_started